 
export const statsData = [
  { value: "13+", label: "Years", description: "Serving the UAE businesses" },
  { value: "1500+", label: "Clients", description: "From SMEs to enterprises" },
  { value: "150+", label: "Experts", description: "Fast, focused & certified" },
  { value: "4500+", label: "Projects", description: "Delivered across sectors" },
]; 
 export const partnersData = [
  { src: "/assets/images/home/partners/client1.svg", alt: "" },
  { src: "/assets/images/home/partners/client2.svg", alt: "" },
  { src: "/assets/images/home/partners/client3.svg", alt: "" },
  { src: "/assets/images/home/partners/client4.svg", alt: "" },
  { src: "/assets/images/home/partners/client5.svg", alt: "" },
  { src: "/assets/images/home/partners/client6.svg", alt: "" },
  { src: "/assets/images/home/partners/client7.svg", alt: "" },
  { src: "/assets/images/home/partners/client8.svg", alt: "" },
  { src: "/assets/images/home/partners/client9.svg", alt: "" },
  { src: "/assets/images/home/partners/client10.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client12.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client13.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client14.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client15.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client16.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client17.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client18.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client19.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client13.svg", alt: "" }, 
];
export const ClienteleData = [
  { src: "/assets/images/home/org/org1.svg", alt: "" },
  { src: "/assets/images/home/org/org2.svg", alt: "" },
  { src: "/assets/images/home/org/org3.svg", alt: "" },
  { src: "/assets/images/home/org/org4.svg", alt: "" },
  { src: "/assets/images/home/org/org5.svg", alt: "" },
  { src: "/assets/images/home/org/org6.svg", alt: "" },
  { src: "/assets/images/home/org/org7.svg", alt: "" },
  { src: "/assets/images/home/org/org8.svg", alt: "" },
  { src: "/assets/images/home/org/org9.svg", alt: "" },
  { src: "/assets/images/home/org/org10.svg", alt: "" },
  { src: "/assets/images/home/org/org11.svg", alt: "" },
  { src: "/assets/images/home/org/org12.svg", alt: "" },
  { src: "/assets/images/home/org/org13.svg", alt: "" }, 
  { src: "/assets/images/home/org/org14.svg", alt: "" },
  { src: "/assets/images/home/org/org15.svg", alt: "" },
  { src: "/assets/images/home/org/org16.svg", alt: "" },
  { src: "/assets/images/home/org/org17.svg", alt: "" },
  { src: "/assets/images/home/org/org18.svg", alt: "" },
  { src: "/assets/images/home/org/org19.svg", alt: "" },
  { src: "/assets/images/home/org/org20.svg", alt: "" },
  { src: "/assets/images/home/org/org21.svg", alt: "" },
  { src: "/assets/images/home/org/org22.svg", alt: "" },
  { src: "/assets/images/home/org/org23.svg", alt: "" },
  { src: "/assets/images/home/org/org24.svg", alt: "" },
  { src: "/assets/images/home/org/org25.svg", alt: "" },
  { src: "/assets/images/home/org/org26.svg", alt: "" },
  { src: "/assets/images/home/org/org27.svg", alt: "" },
  { src: "/assets/images/home/org/org28.svg", alt: "" },
  { src: "/assets/images/home/org/org29.svg", alt: "" },
  
];