 
export const statsData = [
  { value: "13+", label: "Years", description: "Serving the UAE businesses" },
  { value: "1500+", label: "Clients", description: "From SMEs to enterprises" },
  { value: "150+", label: "Experts", description: "Fast, focused & certified" },
  { value: "4500+", label: "Projects", description: "Delivered across sectors" },
]; 
 export const partnersData = [
  { src: "/assets/images/home/partners/client1.svg", alt: "" },
  { src: "/assets/images/home/partners/client2.svg", alt: "" },
  { src: "/assets/images/home/partners/client3.svg", alt: "" },
  { src: "/assets/images/home/partners/client4.svg", alt: "" },
  { src: "/assets/images/home/partners/client5.svg", alt: "" },
  { src: "/assets/images/home/partners/client6.svg", alt: "" },
  { src: "/assets/images/home/partners/client07.svg", alt: "" },
  { src: "/assets/images/home/partners/client8.svg", alt: "" },
  { src: "/assets/images/home/partners/client9.svg", alt: "" },
  { src: "/assets/images/home/partners/client10.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client12.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client13.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client14.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client15.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client16.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client17.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client18.svg", alt: "" }, 
  { src: "/assets/images/home/partners/client19.svg", alt: "" }, 
  // { src: "/assets/images/home/partners/client13.svg", alt: "" }, 
];
export const ClienteleData = [
  { src: "/assets/images/home/org/org1.svg", alt: "" },
  { src: "/assets/images/home/org/org2.svg", alt: "" },
  { src: "/assets/images/home/org/org3.svg", alt: "" },
  { src: "/assets/images/home/org/org4.svg", alt: "" },
  { src: "/assets/images/home/org/org5.svg", alt: "" },
  { src: "/assets/images/home/org/org6.svg", alt: "" },
  { src: "/assets/images/home/org/org7.svg", alt: "" },
  { src: "/assets/images/home/org/org8.svg", alt: "" },
  { src: "/assets/images/home/org/org9.svg", alt: "" },
  { src: "/assets/images/home/org/org10.svg", alt: "" },
  { src: "/assets/images/home/org/org11.svg", alt: "" },
  { src: "/assets/images/home/org/org12.svg", alt: "" },
  { src: "/assets/images/home/org/org13.svg", alt: "" }, 
  { src: "/assets/images/home/org/org14.svg", alt: "" },
  { src: "/assets/images/home/org/org15.svg", alt: "" },
  { src: "/assets/images/home/org/org16.svg", alt: "" },
  { src: "/assets/images/home/org/org17.svg", alt: "" },
  { src: "/assets/images/home/org/org18.svg", alt: "" },
  { src: "/assets/images/home/org/org19.svg", alt: "" },
  { src: "/assets/images/home/org/org20.svg", alt: "" },
  { src: "/assets/images/home/org/org21.svg", alt: "" },
  { src: "/assets/images/home/org/org22.svg", alt: "" },
  { src: "/assets/images/home/org/org23.svg", alt: "" },
  { src: "/assets/images/home/org/org24.svg", alt: "" },
  { src: "/assets/images/home/org/org25.svg", alt: "" },
  { src: "/assets/images/home/org/org26.svg", alt: "" },
  { src: "/assets/images/home/org/org27.svg", alt: "" },
  { src: "/assets/images/home/org/org28.svg", alt: "" },
  { src: "/assets/images/home/org/org29.svg", alt: "" },
  
];

export const testimonialsData = [
  {
    image: "/assets/images/home/alissar.jpg",
    name: "Alissar Nasrallah",
    role: "Regional Marcomms Manager - Gulf Cryo",
    companyLogo: "/assets/images/home/gulf-cryo.svg",
    quote: "Caring team, looks out for what you want and makes sure to give you the outcome you want, quick, you'll find them next to you in critical moments.",
  },
  {
    image: "/assets/images/home/karim.jpg",
    name: "Karim El Shennawy",
    role: "Business Development Director",
    companyLogo: "/assets/images/home/asgc.svg",
    quote: "Global Surf proved to be talented group that delivered their project in excellent manner. They are responsive, and we trusted them day by day with more tasks and they continue to prove their capabilities.",
  },
  {
    image: "/assets/images/home/us.jpg",
    name: "Omar Mohd Bin Dhaher Almheiri",
    role: "President - Prestige",
    companyLogo: "/assets/images/home/prestige.svg",
    quote: "We have a very good experience and relationship with your that is highly professional. We would also like to mention the extra care got from your team. We look forward to continuing this relationship for combined success in the future.",
  },
  {
    image: "/assets/images/home/us.jpg",
    name: "Julius Peter Kinyera",
    role: "General Manager - Royal Blinds LLC",
    companyLogo: "/assets/images/home/royal-blinds.svg",
    quote: "Always available when you need. And they professional IT services",
  },
];

export const TrustedbyData = [
  { src: "/assets/images/itamc/icon1.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon2.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon3.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon4.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon5.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon6.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon7.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon8.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon9.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon10.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon11.svg", alt: "" }, 
  { src: "/assets/images/itamc/icon12.svg", alt: "" }, 
  
];